# k8s-manifests/frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  type: LoadBalancer # Use LoadBalancer to expose the app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80